---
sample_segment: 
  under_window:  50
  seq_len:  10
  stride:  1
  sliding_mode:  start
  sampling: True

model:  
  epochs:  10
  bs:  32
  num_workers:  2

optuna:
  epochs:  50
  trials:  100

