---
sample_segment: 
  under_window:  50
  seq_len:  7
  stride:  1
  sliding_mode:  start
  sampling: True
  all_features:  False

model:  
  epochs:  10
  bs:  32
  num_workers:  2

optuna:
  epochs:  100
  trials:  100

